
# set buffer size for spatial join

buffer_size : 0.00001


# output files
tunnels_output_file: T:\2022October\Joanne\tunnels.shp
#tunnels_output_file:  tunnels.shp

bridges_output_file: T:\2022October\Joanne\bridges.shp
roads_output_file: T:\2022October\Joanne\roads.shp