nearby_zones:
  outfile: node_distance.csv
  delimiter: comma  # options: space, comma, tab
  header: True
  cols:
    - a_node_id
    - b_node_id
    - a_zone_id
    - b_zone_id
    - a_connector_dist  # dist from a_zone to nearest node
    - b_connector_dist  # dist from b_zone to nearest node
    - node_to_node_dist
    - total_dist  # total distance from a_zone to b_zone


network_files:
  # use 1-based consecutive ids for network nodes instead of IDs from OSM
  remap_osm_ids: True
  zone_to_node:
    outfile: ParcelNode.dat
    delimiter: space
  node_distances:
    outfile: NodeDistances.dat
    delimiter: space
  node_indices:
    outfile: NodeIndex.dat
    delimiter: space
